# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3eb83caad81988f0a8c41b97fcfc8eb0dfc92b60282328b9f149b0373b1243664b21c3c3be7b7b4bf2bec3610fecb9e1ec602168f4a81288e6195bf2168c9ca8

test:
  secret_key_base: 5ee9376afbc6b9121a645e7149c9089b836e5961cb840853886505c8b0ada01b9dc070d7423966503fb07dadf060569933b0bd41774ea423f87ffa99f2187343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
